name: mono_icons
description: Flutter implementation of the Mono Icons icons pack (https://github.com/mono-company/mono-icons).
version: 1.0.0+2
repository: https://github.com/lorenzOliveto/mono_icons_flutter
author: Lorenzo Oliveto

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: mono_icons
      fonts:
        - asset: assets/mono_icons.ttf